### ISSUE TITLE
Kotlin as an implementation language

### ISSUE THREAD

**Issue by yschimke** [google/mobly-bundled-snippets#160]
Will you accept PRs for new snippets in Kotlin? or just Java?

**Comment by xpconanfan** [comment]
As long as it can be used together with the existing code :)

But we are a bit strict in terms of what to add in this repo, because we don't want it to become a dump ground of each team's test logic like sl4a.

So I'd suggest making a quick proposal before sending PRs to make sure the addition is aligned with this repo's purpose, which is a thin layer on top of commonly used Android APIs.

**Comment by yschimke** [comment]
Thinking about things like controlling a media session.

**Comment by xpconanfan** [comment]
There's a `MediaSnippet` today. Should be ok to add to it?

**Comment by yschimke** [comment]
They seems like very different things, with different APIs, playing audio locally vs controlling a Media Session. But let's discuss with a PR.  I'll raise an issue to track.

**Comment by xpconanfan** [comment]
Sounds good. Closing this one as the question is answered.
